remove name from heartbeat registration/update
meganz/sdk pull request #2234
Opened 2020-09-07 14:58 UTC by polmr

update python beautifier

2020-09-07 15:01 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (387) :+1:

2020-09-07 15:04 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (550) :-1:

2020-09-07 15:06 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (388) :+1:

2020-09-07 15:10 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (551) :-1:

2020-09-07 15:15 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (2896) :+1:

2020-09-07 15:30 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (2897) :+1:

2020-09-07 15:30 UTC, sergiohs84 approved these changes

2020-09-07 16:01 UTC, sergiohs84 commented
Wait for API to not require the `name` to be sent upon registration (currently, it returns EARGS, as expected in the past).

2020-09-09 09:58 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (404) :+1:

2020-09-09 10:06 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (567) :-1:

2020-09-09 10:10 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (2913) :+1:

2020-09-09 12:39 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (407) :+1:

2020-09-09 12:42 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (570) :-1:

2020-09-09 12:50 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (2916) :+1:

2020-09-10 16:31 UTC, sergiohs84 requested changes

2020-09-11 13:50 UTC, polmr commented on src/heartbeats.cpp
> +
refactoring done

2020-09-11 13:56 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (587) :-1:

2020-09-11 13:56 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (424) :+1:

2020-09-11 14:05 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (2933) :+1:

2020-09-11 16:27 UTC, sergiohs84 approved these changes

2020-09-11 16:27 UTC, merged