megaclc: easy building, adjusted windows static/dll setting
meganz/sdk pull request #2353
Opened 2020-11-11 01:22 UTC by mattw-mega

also we must use our adjusted 3rdparty build for libwebsockets

2020-11-11 01:23 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (760) :-1:

2020-11-11 01:41 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (924) :+1:

2020-11-11 01:48 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3268) :+1:

2020-11-11 10:56 UTC, polmr requested changes
if (HAVE_ASIO)
seem to be missing in

2020-11-11 10:56 UTC, polmr commented on contrib/cmake/CMakeLists.txt
> +    set_property(TARGET tool_tcprelay PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>$<${MEGA_LINK_DYNAMIC_CRT}:DLL>")
```suggestion
    if (HAVE_ASIO)
        set_property(TARGET tool_tcprelay PROPERTY MSVC_RUNTIME_LIBRARY 
        "MultiThreaded$<$<CONFIG:Debug>:Debug>$<${MEGA_LINK_DYNAMIC_CRT}:DLL>")
    endif()
```

2020-11-11 21:27 UTC, mattw-mega commented on contrib/cmake/CMakeLists.txt
> +    set_property(TARGET tool_tcprelay PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>$<${MEGA_LINK_DYNAMIC_CRT}:DLL>")
thanks, updated

2020-11-11 21:31 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (780) :+1:

2020-11-11 21:42 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (944) :+1:

2020-11-11 21:50 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3288) :+1:

2020-11-17 10:27 UTC, polmr approved these changes

2020-11-17 20:46 UTC, merged