SDK-1343. Limit logger archived file number
meganz/sdk pull request #2461
Opened 2020-12-22 16:20 UTC by dyuste

2020-12-22 16:25 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1042) :+1:

2020-12-22 16:36 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1215) :+1:

2020-12-22 16:45 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3560) :+1:

2020-12-23 10:40 UTC, polmr requested changes

2020-12-23 16:01 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1058) :+1:

2020-12-23 16:02 UTC, dyuste commented on src/rotativeperformancelogger.cpp
> +                if (extraFileNumber <= 0) break;
Moved right after, but within the else clause (I only decrement if I success to remove the file).

2020-12-23 16:08 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1059) :+1:

2020-12-23 16:11 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1231) :+1:

2020-12-23 16:21 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3576) :+1:

2020-12-23 16:27 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1232) :+1:

2020-12-23 16:46 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3577) :+1:

2020-12-23 17:52 UTC, polmr approved these changes

2020-12-23 17:52 UTC, merged