SDK-1362. Fix issues with remote paths changes in syncs
meganz/sdk pull request #2494
Opened 2021-01-19 09:59 UTC by polmr

updates on remote paths for syncs are only considered for active syncs
after sync revamping. This reverts that and makes notice of inactive
syncs changes in remote paths. Thus allows for apps to notice that and
also be able to re-enable syncs whose remote went to the //bin an back

2021-01-19 10:19 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1391) :+1:

2021-01-19 10:32 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3734) :+1:

2021-01-19 10:51 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1216) :+1:

2021-01-19 11:33 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1394) :+1:

2021-01-19 11:47 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3737) :+1:

2021-01-19 12:28 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1219) :-1:

2021-01-19 18:26 UTC, sergiohs84 reviewed
It looks good to me. But let's wait for @mattw-mega review, please.
Thanks

2021-01-19 18:26 UTC, sergiohs84 commented on src/megaclient.cpp
> +        //syncs.forEachRunningSync([&](Sync* sync) {
```suggestion
```

2021-01-19 23:44 UTC, mattw-mega requested changes
Hi, now that we are using forEachUnifiedSync, it will also process Syncs which have a config but have failed already.   I think once a sync failed, we should not change the reason (eg. sync fails and a week later the root node is moved to the trash.  We shouldn't update the failure code at that time), so we should also add a condition for this processing, that the sync is at least not currently in an error state.

2021-01-20 11:48 UTC, polmr commented
> Hi, now that we are using forEachUnifiedSync, it will also process Syncs which have a config but have failed already. I think once a sync failed, we should not change the reason (eg. sync fails and a week later the root node is moved to the trash. We shouldn't update the failure code at that time), so we should also add a condition for this processing, that the sync is at least not currently in an error state.

Ey Matt, there is a check in place for us.mSync (there is an active sync) before changing the state [failSync]:-)
I'm pushing a commit to move the check up, to avoid looping to find the rubbish bin and clarify the code a little bit.

2021-01-20 12:04 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1408) :+1:

2021-01-20 12:13 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3751) :+1:

2021-01-20 12:43 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1234) :+1:

2021-02-01 12:27 UTC, vtmateos commented
Tested ok on macOS.

2021-02-01 13:04 UTC, sergiohs84 approved these changes

2021-02-01 13:22 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1489) :+1:

2021-02-01 13:48 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3832) :+1:

2021-02-01 15:20 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1314) :+1:

2021-02-01 20:06 UTC, mattw-mega approved these changes

2021-02-01 20:13 UTC, merged