SDK-1331. Persistance of sync configs after logout
meganz/sdk pull request #2523
Opened 2021-02-01 18:46 UTC by sergiohs84

2021-02-01 18:53 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (1492) :-1:

2021-02-01 19:02 UTC, JenkinsMega commented
megasdk_PR FAILED  (3835) :-1:

2021-02-01 19:30 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1317) :-1:

2021-02-01 20:09 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs FAILED  (1493) :-1:

2021-02-01 20:18 UTC, JenkinsMega commented
megasdk_PR FAILED  (3836) :-1:

2021-02-01 20:46 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1318) :-1:

2021-02-01 21:44 UTC, dwmega approved these changes

2021-02-02 00:43 UTC, mattw-mega requested changes
There is actually already a branch and a PR for this - using a subset of the command set that David added for Backup months ago, so that one is much more compatible with future merges - I think we should close this one.  task/merge_megacli_updated_sync_commands_for_backup
I'll be merging the latest JSON config changes to that one today and double checking the 1331 expected behaviour.  thanks

2021-02-03 18:59 UTC, sergiohs84 commented
Superseeded by https://github.com/meganz/sdk/pull/2526

2021-02-03 18:59 UTC, closed without merging