WIP:SDK-1341: Feature/get node favourite
meganz/sdk pull request #2531
Opened 2021-02-03 19:55 UTC by ms-mega

2021-02-04 18:46 UTC, ms-mega commented
trigger compilation

2021-02-04 19:00 UTC, ms-mega commented
trigger compilation

2021-02-04 19:02 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1532) :+1:

2021-02-04 19:14 UTC, JenkinsMega commented
megasdk_PR FAILED  (3875) :-1:

2021-02-04 19:18 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1533) :+1:

2021-02-04 19:18 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1357) :+1:

2021-02-04 19:40 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3876) :+1:

2021-02-04 19:54 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1358) :-1:

2021-02-05 04:46 UTC, ms-mega commented
trigger compilation

2021-02-05 05:01 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1543) :+1:

2021-02-05 05:13 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3886) :+1:

2021-02-05 05:24 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1368) :+1:

2021-02-05 12:46 UTC, sergiohs84 requested changes

2021-02-05 12:46 UTC, sergiohs84 commented on include/megaapi.h
> +            TYPE_SET_ATTR_NODE, TYPE_GET_ATTR_NODE, TYPE_CHAT_CREATE, TYPE_CHAT_FETCH, TYPE_CHAT_INVITE,
Also, for any new type of request, we add it to the `MegaRequestPrivate::getRequestString()`

2021-02-05 12:46 UTC, sergiohs84 commented on include/megaapi.h
> +         *
The information about the type of request and the valid members is missing. See others for reference, please.

2021-02-05 12:52 UTC, sergiohs84 requested changes

2021-02-05 12:52 UTC, sergiohs84 commented on tests/integration/SdkTest_test.cpp
> +            mMegaFavNodeList = request->getMegaNodeList()->copy();
You are accumulating a memory leak here, every time you make a copy, the previous allocated memory is leaked.

2021-02-05 14:34 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3894) :+1:

2021-02-05 14:56 UTC, JenkinsMega commented
megasdk-winx64-PRs SUCCEDED (1376) :+1:

2021-02-05 15:16 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1551) :+1:

2021-02-08 07:28 UTC, sergiohs84 commented on tests/integration/SdkTest_test.cpp
> +            mMegaFavNodeList = request->getMegaNodeList()->copy();
Fixed in 8f5d15a

2021-02-08 07:29 UTC, sergiohs84 approved these changes

2021-02-08 13:01 UTC, merged