Update search Android bindings
meganz/sdk pull request #2556
Opened 2021-02-17 11:53 UTC by Yenel

2021-02-17 12:20 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3938) :+1:

2021-02-17 12:48 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1595) :+1:

2021-02-17 12:57 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1421) :-1:

2021-02-17 13:54 UTC, jgandres submitted a review, later dismissed

2021-02-17 14:04 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1597) :+1:

2021-02-17 14:26 UTC, JenkinsMega commented
megasdk_PR FAILED  (3940) :-1:

2021-02-17 15:40 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1423) :-1:

2021-02-18 12:14 UTC, javiergm1983 requested changes
Hi @Yenel there are incorrect bindings, please review it.

2021-02-18 12:14 UTC, javiergm1983 commented on bindings/java/nz/mega/sdk/MegaApiJava.java
> +        return nodeListToArray(megaApi.search(searchString, cancelToken, order));
This binding should call to `MegaApi::searchOnInShares()`
```suggestion
        return nodeListToArray(megaApi.searchOnInShares(searchString, cancelToken, order));
```

2021-02-18 12:14 UTC, javiergm1983 commented on bindings/java/nz/mega/sdk/MegaApiJava.java
>          return nodeListToArray(megaApi.search(searchString, cancelToken, order));
This binding should call to MegaApi::searchOnOutShares()
```suggestion
        return nodeListToArray(megaApi.searchOnOutShares(searchString, cancelToken, order));
```

2021-02-18 12:14 UTC, javiergm1983 commented on bindings/java/nz/mega/sdk/MegaApiJava.java
> +        return nodeListToArray(megaApi.search(searchString, cancelToken, order));
This binding should call to MegaApi::searchOnPublicLinks()
```suggestion
        return nodeListToArray(megaApi.searchOnPublicLinks(searchString, cancelToken, order));
```

2021-02-18 12:34 UTC, Yenel commented
Hi @javiergm1983, the bindings you pointed out are now fixed. Please check it again. Thanks.

2021-02-18 12:40 UTC, javiergm1983 approved these changes
No everything seems ok.

2021-02-18 12:40 UTC, merged

2021-02-18 12:51 UTC, JenkinsMega commented
megasdk-crossAndroid-PRs SUCCEDED (1612) :+1:

2021-02-18 13:00 UTC, JenkinsMega commented
megasdk_PR SUCCEDED (3955) :+1:

2021-02-18 18:26 UTC, JenkinsMega commented
megasdk-winx64-PRs FAILED  (1438) :-1:

2021-02-18 23:07 UTC, dwmega commented
trigger compilation